services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "${DATABASE_DB}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
          - "5432:5432"
  redis:
    image: redis:7
    ports:
        - "6379:6379"

  mqtt:
      image: eclipse-mosquitto:2
      ports:
      - "1883:1883"
      volumes:
      - ./conf/mosquitto:/mosquitto/config

volumes:
  postgres_data:
